#Question_1

'''
1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.
'''

In [1]:
class Employee:
    
    #creating Employee class with name, family, salary and department
    
    count_of_employees = 0
    # create a data member to count the number of Employees

    def __init__(self, name, family, salary, department): #constructor which exucutes without creating an object
        self.__name = name
        self.__family = family
        self.salary = salary
        self.__department = department
        Employee.count_of_employees += 1

    @staticmethod 
    def avg_salary(employees):  
        #create a function to calculate average salary 
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.count_of_employees

class FulltimeEmployee(Employee):
    
    #FullTimeEmployee is a sub class of Employee
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

    def full_time_benefits(self):
        print("Full time employee's Details:")


def main():
    employees = []
    fulltimeemp1 = FulltimeEmployee("Saikumar", "Fam_1", 160000, "Human Resources")
    fulltimeemp1.full_time_benefits()
    employees.append(fulltimeemp1)
    fulltimeemp2 = FulltimeEmployee("Bhanu", "Fam_2", 120000, "Bigdata Team")
    employees.append(fulltimeemp2)
    e1 = Employee("Vijay", "Fam_3", 110000, "Tech support")
    employees.append(e1)
    e2 = Employee("Rohit", "Fam_4", 140000, "Marketing")
    employees.append(e2)
    print("Average salary:", FulltimeEmployee.avg_salary(employees))
    print("Number of Employees :" + str(Employee.count_of_employees))


if __name__ == "__main__":
    main()

Full time employee's Details:
Average salary: 132500.0
Number of Employees :4


#Question_2

'''
2. Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)
'''

In [3]:
import numpy as np
rand = np.random.uniform(1,20,20) #creating random vector of size 20 which is having only float in the range 1-20.
print("Original array:")
print(rand)
rand=np.reshape(rand,(4,5),order='c') #Reshape the array to 4 by 5 order
print(rand)
print(np.shape(rand)) #Displays array shape
maxNum = np.amax(rand, axis=1)
rand=np.where(np.isin(rand,maxNum), 0, rand) #Replace's the max in each row by '0'.
print("Maximum value of each row replaced by 0:")
print(rand)

Original array:
[14.88698082 19.80559655 19.97644989  2.84214538  7.58687522 19.68690547
 15.9157924   3.00566178 14.20937933  3.06223332  2.10464969  4.64128671
 12.14766852  4.15558317 12.10274154 18.74076878  8.6551659  19.50782278
  2.71201296  2.82775526]
[[14.88698082 19.80559655 19.97644989  2.84214538  7.58687522]
 [19.68690547 15.9157924   3.00566178 14.20937933  3.06223332]
 [ 2.10464969  4.64128671 12.14766852  4.15558317 12.10274154]
 [18.74076878  8.6551659  19.50782278  2.71201296  2.82775526]]
(4, 5)
Maximum value of each row replaced by 0:
[[14.88698082 19.80559655  0.          2.84214538  7.58687522]
 [ 0.         15.9157924   3.00566178 14.20937933  3.06223332]
 [ 2.10464969  4.64128671  0.          4.15558317 12.10274154]
 [18.74076878  8.6551659   0.          2.71201296  2.82775526]]
